version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    # container_name: ollama  <-- HAPUS INI (Biar Dokploy yang atur namanya)
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=2m
      - OLLAMA_NUM_PARALLEL=1
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    # container_name: open-webui <-- HAPUS INI JUGA
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=d8s9d8s_Ac0d3my_Juar4_2026_!@#
    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      ollama:
        condition: service_healthy
    # Tambahkan ini agar Dokploy lebih mudah mendeteksi port internal
    expose:
      - 8080
    networks:
      - dokploy-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama_data:
  open-webui_data:

networks:
  dokploy-network:
    external: true
